In [1]:
import pandas as pd 
import mysql.connector
from sqlalchemy import create_engine # type: ignore

In [2]:
connection = mysql.connector.connect( host="localhost", user="root", password="saif.123456789", database="movie_rental" ) 
print("Connected to OLTP Database")

Connected to OLTP Database

In [3]:
dw_connection = mysql.connector.connect( host="localhost", user="root", password="saif.123456789", database="movie_rental_dw" ) 
print("Connected to DW Database")

Connected to DW Database

In [4]:
engine = create_engine( "mysql+mysqlconnector://root:saif.123456789@localhost/movie_rental_dw" )
print("Engine Created Successfully")

Engine Created Successfully

In [5]:
dim_film = pd.read_sql("""
SELECT
    film.film_id,
    film.title,
    category.name AS category
FROM film
JOIN film_category
    ON film.film_id = film_category.film_id
JOIN category
    ON film_category.category_id = category.category_id
""", connection)

C:\Users\adhdh\AppData\Local\Temp\ipykernel_3864\2901569852.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dim_film = pd.read_sql("""

In [6]:
dim_film.head()

   film_id                title category
0       19         AMADEUS HOLY   Action
1       21      AMERICAN CIRCUS   Action
2       29   ANTITRUST TOMATOES   Action
3       38        ARK RIDGEMONT   Action
4       56  BAREFOOT MANCHURIAN   Action

In [7]:
dim_film.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   film_id   1000 non-null   int64
 1   title     1000 non-null   str
 2   category  1000 non-null   str
dtypes: int64(1), str(2)
memory usage: 23.6 KB

In [8]:
dim_film = dim_film.drop_duplicates()

In [ ]:
dim_film.to_sql(
    name='dim_film',
    con=engine,
    if_exists='append',
    index=False
)

print("DIM_FILM Loaded Successfully")

In [ ]:
dim_customer = pd.read_sql("""
SELECT
    customer.customer_id,
    CONCAT(customer.first_name,' ',customer.last_name) AS full_name,
    country.country
FROM customer
JOIN address
    ON customer.address_id = address.address_id
JOIN city
    ON address.city_id = city.city_id
JOIN country
    ON city.country_id = country.country_id
""", connection)

C:\Users\adhdh\AppData\Local\Temp\ipykernel_15948\2494433666.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dim_customer = pd.read_sql("""

In [ ]:
dim_customer = dim_customer.drop_duplicates()

In [ ]:
dim_customer.head()

In [ ]:
dim_customer.to_sql(
    name='dim_customer',
    con=engine,
    if_exists='append',
    index=False
)

print("DIM_CUSTOMER Loaded Successfully")

DIM_CUSTOMER Loaded Successfully

In [ ]:
fact_rental = pd.read_sql("""
SELECT
    rental.rental_id,
    rental.customer_id,
    inventory.film_id,
    DATEDIFF(rental.return_date, rental.rental_date) AS rental_days
FROM rental
JOIN inventory
    ON rental.inventory_id = inventory.inventory_id
""", connection)

C:\Users\adhdh\AppData\Local\Temp\ipykernel_15948\3613592242.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  fact_rental = pd.read_sql("""

In [ ]:
fact_rental = fact_rental.drop_duplicates()

In [ ]:
fact_rental.head()

   rental_id  customer_id  film_id  rental_days
0       4863          431        1          3.0
1      11433          518        1          9.0
2      14714          279        1          9.0
3        972          411        1          7.0
4       2117          170        1          6.0

In [ ]:
fact_rental.to_sql(
    name='fact_rental',
    con=engine,
    if_exists='append',
    index=False
)

print("FACT_RENTAL Loaded Successfully")

FACT_RENTAL Loaded Successfully

In [ ]:
fact_payment = pd.read_sql("""
SELECT
    payment_id,
    customer_id,
    amount
FROM payment
""", connection)

C:\Users\adhdh\AppData\Local\Temp\ipykernel_15948\1553754342.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  fact_payment = pd.read_sql("""

In [ ]:
fact_payment = fact_payment.drop_duplicates()

In [ ]:
fact_payment.head()

In [ ]:
fact_payment.to_sql(
    name='fact_payment',
    con=engine,
    if_exists='append',
    index=False
)

print("FACT_PAYMENT Loaded Successfully")

FACT_PAYMENT Loaded Successfully

In [10]:
fact_inventory = pd.read_sql("""
SELECT
    inventory_id,
    film_id,
    store_id,
    1 AS inventory_count
FROM inventory
""", connection)

C:\Users\adhdh\AppData\Local\Temp\ipykernel_3864\3847295249.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  fact_inventory = pd.read_sql("""

In [ ]:
fact_inventory = fact_inventory.drop_duplicates()

In [ ]:
fact_inventory.head()

   inventory_id  film_id  store_id  inventory_count
0             1        1         1                1
1             2        1         1                1
2             3        1         1                1
3             4        1         1                1
4            16        4         1                1

In [ ]:
fact_inventory.to_sql(
    name='fact_inventory',
    con=engine,
    if_exists='append',
    index=False
)

print("FACT_INVENTORY Loaded Successfully")

FACT_INVENTORY Loaded Successfully